config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  get '/profile', to: 'users#show'
  get '/vote', to: 'candidates#index'
  get '/live', to: 'candidates#live'
  get '/candidates/:number', to: 'candidates#show', as: 'candidate'
  post '/candidates/:number/vote', to: 'candidates#vote', as: 'vote_candidate'

  root to: redirect('/profile')
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate_attribute.rb
# frozen_string_literal: true

class CandidateAttribute < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

require 'securerandom'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable, :confirmable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable,
         :recoverable, :rememberable, :validatable

  has_one :candidate_attribute, dependent: :destroy
  has_one :vote, foreign_key: 'constituent_id', inverse_of: :constituent, dependent: :nullify
  has_many :votes, foreign_key: 'candidate_id', inverse_of: :candidate, dependent: :nullify

  scope :candidates, -> { joins(:candidate_attribute) }

  before_validation :set_default_password,
                    on: :create,
                    if: -> { password.nil? && password_confirmation.nil? }
  validates :name, presence: true
  validates :sidn, presence: true, uniqueness: true

  delegate :number, :vision, :mission, to: :candidate_attribute, allow_nil: true

  def candidate?
    !candidate_attribute.nil?
  end

  def voted?
    !vote.nil?
  end

  def can_vote?
    !voted? && eligible?
  end

  private

  def set_default_password
    password = SecureRandom.hex
    self.password = password
    self.password_confirmation = password
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :candidate, class_name: 'User', inverse_of: :votes
  belongs_to :constituent, class_name: 'User', inverse_of: :vote
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
# frozen_string_literal: true

class CandidatesController < ApplicationController
  before_action :authenticate_user!, except: %i[show live]
  before_action :redirect_if_cannot_vote!, except: %i[show live]

  def index
    @candidates = User.candidates.order('candidate_attributes.number ASC')

    respond_to do |format|
      format.html do
        redirect_back fallback_location: profile_path, alert: 'Tidak ada kandidat yang tersedia.' if @candidates.empty?
      end
    end
  end

  def show
    @candidate = User.candidates.find_by(candidate_attributes: { number: params[:number] })

    respond_to do |format|
      format.html do
        redirect_back fallback_location: profile_path, alert: "Tidak ada kandidat bernomor #{params[:number]}." if @candidate.nil?
      end
    end
  end

  def vote
    respond_to do |format|
      format.html do
        @candidate = User.candidates.find_by(candidate_attributes: { number: params[:number] })

        if @candidate.nil?
          redirect_to vote_path, alert: 'Tidak bisa memilih seorang yang bukan kandidat.'
        else
          vote = Vote.create(constituent: current_user, candidate: @candidate)

          if vote.persisted?
            render :thank_you
          else
            logger.error "[ERROR] Couldn't vote: #{vote.errors.full_messages.join(', ')}."
            redirect_to vote_path, alert: 'Tidak bisa memilih. Cobalah beberapa saat lagi.'
          end
        end
      end
    end
  end

  def live
    @candidates = User.candidates.order('candidate_attributes.number ASC')

    respond_to do |format|
      format.html
      format.json do
        render json: {
          votes: @candidates.map { |candidate| candidate.votes.count }
        }
      end
    end
  end

  private

  def redirect_if_cannot_vote!
    return if current_user.can_vote?

    respond_to do |format|
      format.html do
        redirect_back fallback_location: profile_path, alert: 'Tidak bisa mengakses karena tidak bisa memilih!'
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    user
  end

  private

  def user
    @user ||= current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include AssetsHelper
  include BootstrapHelper
  include FeatherHelper

  def navbar_link_content(icon, text)
    tag.i(class: 'me-1', 'data-feather': icon) +
      tag.span(text, class: 'd-none d-md-inline-block')
  end

  def navbar_link(icon, text, path, **options)
    link_to navbar_link_content(icon, text), path, options.merge!(class: 'link-light text-decoration-none')
  end

  def navbar_link_unless(condition, icon, text, path, **options)
    if condition
      tag.div navbar_link_content(icon, text), class: 'text-light opacity-75'
    else
      navbar_link(icon, text, path, **options)
    end
  end
end

app/helpers/assets_helper.rb
# frozen_string_literal: true

module AssetsHelper
  def asset_exists?(path)
    if Rails.env.production?
      !Rails.application.assets_manifest.find_sources(path).nil?
    else
      !Rails.application.assets.find_asset(path).nil?
    end
  end
end

app/helpers/bootstrap_helper.rb
# frozen_string_literal: true

module BootstrapHelper
  def bootstrap_flash_color(type)
    case type.to_sym
    when :alert
      'danger'
    when :notice
      'info'
    else
      'info'
    end
  end
end

app/helpers/candidates_helper.rb
# frozen_string_literal: true

module CandidatesHelper
end

app/helpers/feather_helper.rb
# frozen_string_literal: true

module FeatherHelper
  def feather_flash_icon(type)
    case type.to_sym
    when :alert
      'alert-triangle'
    when :notice
      'info'
    else
      'info'
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/candidates/index.html.erb
<div class="w-100 h-100 d-flex justify-content-center align-items-center">
  <div class="mw-md-50">
    <div class="row g-5">
      <% @candidates.each do |candidate| %>
        <%= form_with url: vote_candidate_path(candidate.number), class: 'col-sm-6' do |form| %>
          <div class="card">
            <%
              image_path =
                asset_exists?("candidates/#{candidate.sidn}.jpg") ?
                  "candidates/#{candidate.sidn}.jpg" :
                  'candidate-placeholder.jpg'
            %>
            <div class="candidate-number d-flex justify-content-center align-items-center">
              <%= candidate.number %>
            </div>
            <%= image_tag image_path, class: 'card-img-top', style: 'object-fit:cover;height:250px', alt: candidate.name %>
            <div class="card-body text-center">
              <h2 class="card-title fs-5"><%= candidate.name %></h2>
              <div class="d-flex flex-column">
                <%= form.submit 'Pilih!', class: 'btn btn-primary mb-1' %>
                <%= link_to 'Lihat Profil', candidate_path(candidate.number), class: 'small link-secondary text-decoration-none' %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/candidates/live.html.erb
<div class="w-100 h-100 d-flex align-items-center justify-content-center">
  <div class="card mw-md-50 p-3 text-center">
    <% if @candidates.count > 1 %>
      <h1 class="fs-5 fw-bold">Perhitungan Suara <span class="badge bg-danger">LIVE</span></h1>
      <canvas id="livecount-chart" width="400" height="400" class="mb-3"></canvas>
      <div class="small text-muted">
        Terakhir kali diperbaharui: <span id="time-of-update">belum ada</span>
      </div>
    <% else %>
      Jumlah kandidat belum cukup.
    <% end %>
  </div>
</div>

<% if @candidates.count > 1 %>
  <script>
    (() => {
      if (liveCountChart) liveCountChart.destroy();
      var liveCountChart = new Chart(
        document.getElementById('livecount-chart').getContext('2d'),
        {
          type: 'pie',
          data: {
            labels: [
              <%= @candidates.map { |candidate| "'#{candidate.name}'"}.join(', ').html_safe %>
            ],
            datasets: [{
              label: 'Perhitungan Suara',
              data: [
                <%= @candidates.map { |candidate| candidate.votes.count }.join(', ') %>
              ],
              backgroundColor: [
                <%= Array.new(@candidates.count) { "'##{Random.bytes(3).unpack1('H*')}'" }.join(', ').html_safe %>
              ],
              hoverOffset: 4
            }]
          },
          options: {
            plugins: {
              tooltip: {
                enabled: false
              },
              datalabels: {
                formatter: (value, ctx) => {
                  let sum = 0;
                  let dataArr = ctx.chart.data.datasets[0].data;
                  dataArr.map(data => {
                      sum += data;
                  });
                  let percentage = (value*100 / sum).toFixed(2)+"%";
                  return percentage;
                },
                color: '#fff',
              }
            }
          }
        }
      );

      if (intervalToUpdateLiveCount) clearInterval(intervalToUpdateLiveCount);
      var intervalToUpdateLiveCount = setInterval(() => {
        document.getElementById('time-of-update').textContent = dayjs().format('DD/MM/YYYY HH:mm:ss Z');

        $.ajax({
          url: '<%= live_path :json %>',
          method: 'GET',
          success: (data) => {
          liveCountChart.data.datasets[0].data = data.votes;
          liveCountChart.update();
          }
        });
      }, 10000);
    })();
  </script>
<% end %>

app/views/candidates/show.html.erb
<div class="d-flex justify-content-center align-items-center w-100 h-100">
  <section class="card w-100 p-3 mb-3 align-items-center" style="max-width:50rem">
    <h1 class="mb-3 fs-5 fw-bold">Kandidat Nomor <%= @candidate.number %></h1>
    
    <div class="w-100">
      <div class="mb-3 d-flex justify-content-center w-100">
        <%
          image_path =
            asset_exists?("candidates/#{@candidate.sidn}.jpg") ?
              "candidates/#{@candidate.sidn}.jpg" :
              'candidate-placeholder.jpg'
        %>
        <%= image_tag image_path, class: 'mw-sm-50 img-thumbnail' %>
      </div>
      <% %i[name sidn vision mission].each do |attribute| %>
        <% value = @candidate.send(attribute) %>
        <% next if value.nil? %>
        <div class="row">
          <div class="col-3 col-md-2 border-end border-dark text-end">
            <%= t("activerecord.attributes.user.#{attribute.to_s}") %>
          </div>
          <div class="col-9 col-md-10 text-muted">
            <div class="d-flex align-items-center">
              <%= value %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="mt-3 d-flex justify-content-center w-100">
        <%= button_tag 'Kembali', onclick: 'javascript:history.back()', class: 'btn btn-primary' %>
      </div>
    </div>
  </section>
</div>

app/views/candidates/thank_you.html.erb
<div class="w-100 h-100 d-flex flex-column align-items-center justify-content-center">
  <section class="card w-100 p-3 mb-3 text-center" style="max-width:30rem">
    <h1 class="fs-3 fw-bold">Terima kasih!</h1>
    <p>
      Suara kamu telah masuk ke dalam sistem.
      Terima kasih telah berpartisipasi dalam pemilihan ini.
    </p>
    <p class="text-muted small">
      Dalam <span id="time-to-logout">10</span> detik kamu akan dikeluarkan secara otomatis.
    </p>
    <script>
      (() => {
        let secondsToLogout = 10;

        if (intervalToLogout) clearInterval(intervalToLogout);
        var intervalToLogout = setInterval(() => {
          document.getElementById('time-to-logout').textContent = --secondsToLogout;

          if (secondsToLogout <= 0) {
            $.ajax({
              url: '<%= destroy_user_session_path %>',
              headers: {
                'X-CSRF-Token': document.getElementsByName("csrf-token")[0].content
              },
              method: 'DELETE',
              success: () => {
                window.location.href = '<%= new_user_session_path %>'
              }
            });
            clearInterval(intervalToLogout);
          }
        }, 1000);
      })();
    </script>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="id">
  <head>
    <title>E-Votif</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="vh-100 overflow-hidden">
    <nav class="nav top-nav fixed-top navbar-dark bg-dark shadow">
      <div class="container h-100 navbar">
        <%= link_to root_path, class: 'navbar-brand d-flex align-items-center' do %>
          <!-- This is temporary logo for this app -->
          <%= image_tag 'himatif-logo.png', class: 'me-2 bg-white', style: 'border-radius:100%;height:2.5rem' %>
          E-Votif
        <% end %>
        <ul class="list-unstyled d-flex m-0">
          <li class="me-4">
            <%= navbar_link_unless current_page?(live_path), 'pie-chart', 'Perhitungan Suara', live_path %>
          </li>
          <% if user_signed_in? %>
            <% if current_user.can_vote? %>
              <li class="me-4">
                <%= navbar_link_unless current_page?(vote_path), 'check-circle', "Pilih", vote_path %>
              </li>
            <% end %>
            <li class="me-4">
              <%= navbar_link_unless current_page?(profile_path), 'user', "Profil", profile_path %>
            </li>
            <li>
              <%= navbar_link 'log-out', "Keluar", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= navbar_link_unless current_page?(new_user_session_path), 'log-in', 'Masuk', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <main class="d-flex flex-column overflow-auto">
      <div class="container flex-fill">
        <%= yield %>
      </div>
    </main>

    <% unless flash.empty? %>
      <div class="toast-container" aria-live="polite" aria-atomic="true">
        <% flash.each do |type, message| %>
          <div
            class="toast d-flex align-items-center text-white border-0 bg-<%= bootstrap_flash_color(type) %>"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          >
            <div class="toast-body d-flex align-items-center">
              <i class="me-2" data-feather="<%= feather_flash_icon(type) %>" width=24 height=24 stroke-width=2></i>
              <%= message %>
            </div>
            <button class="btn-close btn-close-white ms-auto me-2" type="button" data-bs-dismiss="toast" aria-label="Tutup">
          </div>
        <% end %>
      </div>
    <% end %>

    <script>
      feather.replace()
    </script>

    <% unless flash.empty? %>
      <script>
        document.addEventListener('turbolinks:before-cache', () => {
          document.querySelector('.toast-container')?.remove()
        })

        document.addEventListener('turbolinks:load', () => {
          document.querySelectorAll('.toast').forEach(node => {
            let toast = new bootstrap.Toast(node)
            toast.show()
          })
        })
      </script>
    <% end %>

    <%= yield :js %>
  </body>
</html>

app/views/users/show.html.erb
<div class="w-100 h-100 d-flex flex-column align-items-center justify-content-center">
  <section class="card w-100 p-3 mb-3 align-items-center" style="max-width:30rem">
    <h1 class="mb-3 fs-5 fw-bold">Profil Kamu</h1>
    <div class="w-100">
      <% %i[name sidn].each do |attribute| %>
        <% value = @user.send(attribute) %>
        <% next if value.nil? %>
        <div class="row">
          <div class="col-5 border-end border-dark text-end">
            <%= t("activerecord.attributes.user.#{attribute.to_s}") %>
          </div>
          <div class="col-7 text-muted">
            <div class="d-flex align-items-center">
              <%= value %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </section>

  <%
    alert_class =
      if @user.voted?
        'success'
      elsif @user.can_vote?
        'warning'
      else
        'danger'
      end
  %>
  <section class="alert alert-<%= alert_class %> w-100 p-3 d-flex flex-column align-items-center" style="max-width:30rem">
    <div class="text-center">
      <% if @user.voted? %>
        Kamu telah memilih kandidat nomor <%= @user.vote.candidate.number %> bernama <strong><%= @user.vote.candidate.name %></strong>
        pada tanggal <strong><%= l(@user.vote.updated_at) %></strong>.
      <% elsif @user.can_vote? %>
        Kamu <strong>belum</strong> memilih seorang kandidat.
      <% else %>
        Kamu <strong>belum bisa</strong> memilih seorang kandidat.
      <% end %>
    </div>
    <%= link_to 'Pilih!', vote_path, class: 'alert-link text-decoration-none fs-4 fw-bold mt-1' if @user.can_vote? %>
  </section>
</div>